Repository Fantom-foundation/go-lachesis, pull requests merged in 2018-11, with the labels that each got.

#65 Issue #28 finish
  src/dummy/client_test.go
  src/proxy/grpc_app.go
  src/proxy/grpc_lachesis.go
  src/proxy/grpc_test.go
  src/proxy/inmem_test.go
  src/proxy/socket/.gitignore
  src/proxy/socket/app/inmem_app_proxy.go
Labels: enhancement

#69 Improvements to transaction handling & tests
  .gitlab-ci.yml
  cmd/lachesis/commands/run.go
  cmd/lachesis/commands/run_lachesis_multi.go
  makefile
  scripts/multi_run.bash
  src/lachesis/lachesis_config.go
  src/mobile/utils.go
  src/net/client_socket.go
  src/net/client_websocket.go
  src/net/client_websocket_test.go
  src/net/inmem_transport.go
  src/net/inmem_transport_test.go
  src/net/mqtt.go
  src/net/mqtt_test.go
  src/net/net_transport.go
  src/net/server_socket.go
  src/net/server_websocket.go
  src/net/server_websocket_test.go
  src/net/socket.go
  src/net/transport_test.go
  src/node/config.go
  src/node/core.go
  src/node/node.go
  src/node/node_test.go
  src/poset/badger_store.go
  src/poset/poset.go
  src/proxy/grpc_test.go
  src/utils/test_util.go
  src/utils/util.go
  tester/tester.go
Labels: enhancement

#79 Protocol Buffers
  .travis.yml
  cmd/lachesis/commands/config.go
  cmd/lachesis/commands/run.go
  glide.lock
  glide.yaml
  src/log/hook.go
  src/mobile/mobile_app_proxy.go
  src/net/transport_test.go
  src/node/core_test.go
  src/node/debug.go
  src/node/node.go
  src/node/nodebug.go
  src/peers/peer.go
  src/peers/peer.pb.go
  src/poset/badger_store.go
  src/poset/badger_store_test.go
  src/poset/block.go
  src/poset/block.pb.go
  src/poset/block.proto
  src/poset/debug.go
  src/poset/event.go
  src/poset/event.pb.go
  src/poset/event.proto
  src/poset/event_test.go
  src/poset/flagTableWrapper.pb.go
  src/poset/flagTableWrapper.proto
  src/poset/frame.go
  src/poset/frame.pb.go
  src/poset/frame.proto
  src/poset/inmem_store.go
  src/poset/inmem_store_test.go
  src/poset/peer.proto
  src/poset/poset.go
  src/poset/poset_test.go
  src/poset/root.go
  src/poset/root.pb.go
  src/poset/root.proto
  src/poset/roundInfo.go
  src/poset/roundInfo.pb.go
  src/poset/roundInfo.proto
  src/proxy/grpc_app.go
  src/proxy/grpc_lachesis.go
  src/proxy/inmem_app.go
Labels: enhancement

#83 Makefile improvements
  .travis.yml
  Makefile
  README.md
  scripts/dist.sh
  src/Makefile
  src/net/net_transport_test.go
  src/node/node.go
  src/peers/Makefile
  src/peers/peer.proto
  src/poset/Makefile
  src/poset/event.pb.go
  src/poset/event.proto
  src/poset/poset.go
  src/proxy/Makefile
  src/proxy/internal/Makefile
  src/proxy/internal/grpc.pb.go
  tester/tester.go
Labels: enhancement

#84 CheckSelfParent fix, and makefile improvements
  Makefile
  glide.lock
  mage.go
  src/Makefile
  src/node/core.go
  src/pb/wire_block_signature.pb.go
  src/pb/wire_body.pb.go
  src/pb/wire_event.pb.go
  src/peers/Makefile
  src/poset/Makefile
  src/poset/event.go
  src/proto/wire_block_signature.proto
  src/proto/wire_body.proto
  src/proto/wire_event.proto
  src/proxy/internal/Makefile
Labels: bug

#85 Fix `poset` tests related ConsensusPoset test graph.
  src/poset/poset_test.go
Labels: bug

#87 Fix node tests.
  src/difftool/example_test.go
  src/node/common.go
  src/node/core_test.go
  src/node/node_test.go
Labels: bug

#92 Thread safe LRU cache, limit concurrency, improve edge case error handling
  Makefile
  glide.lock
  glide.yaml
  src/common/lru.go
  src/common/lru_test.go
  src/node/common.go
  src/node/core.go
  src/node/counter.go
  src/node/debug.go
  src/node/node.go
  src/node/node_test.go
  src/node/peer_selector2.go
  src/poset/badger_store.go
  src/poset/badger_store_test.go
  src/poset/block.go
  src/poset/block.pb.go
  src/poset/block.proto
  src/poset/event.go
  src/poset/event.pb.go
  src/poset/event.proto
  src/poset/inmem_store.go
  src/poset/poset.go
  src/poset/poset_test.go
  src/proxy/grpc_lachesis.go
Labels: bug, enhancement
