Repository Fantom-foundation/go-lachesis, pull requests merged in 2018-12, with the labels that each got.

#94 Merged graph_fixes
  src/node/graph.go
Labels: enhancement

#96 Demo fix
  .dockerignore
  Dockerfile
  demo/Dockerfile.dummy
  demo/Dockerfile.node
  demo/Makefile
  demo/scripts/bombard.sh
  demo/scripts/build-conf.sh
  demo/scripts/demo.sh
  demo/scripts/run-testnet.sh
  demo/scripts/stop-testnet.sh
  demo/scripts/watch.sh
  src/peers/json_peers.go
Labels: enhancement

#95 Merged network_binary
  Makefile
  cmd/network/commands/config.go
  cmd/network/commands/proxy.go
  cmd/network/commands/root.go
  cmd/network/commands/run.go
  cmd/network/commands/version.go
  cmd/network/main.go
Labels: bug, enhancement

#97 Better edge case handling and initialisation routines
  .travis.yml
  README.md
  cmd/lachesis/commands/run.go
  src/node/core.go
  src/node/debug.go
  src/node/node.go
  src/node/peer_selector2.go
  src/peers/peer.go
  src/peers/peer.pb.go
  src/peers/peer.proto
  src/peers/peers.go
  src/poset/badger_store.go
  src/poset/event.go
  src/poset/event.pb.go
  src/poset/event.proto
  src/poset/poset.go
  src/poset/roundInfo.go
  src/poset/roundInfo.pb.go
  src/poset/roundInfo.proto
  tester/tester.go
Labels: bug, enhancement

#99 Resolve data races, as detected by Go compiler
  Makefile
  cmd/network/commands/version.go
  glide.lock
  glide.yaml
  src/Makefile
  src/common/Makefile
  src/common/rolling_index.go
  src/crypto/Makefile
  src/difftool/Makefile
  src/difftool/example_test.go
  src/dummy/Makefile
  src/dummy/state.go
  src/lachesis/Makefile
  src/log/Makefile
  src/mobile/Makefile
  src/net/Makefile
  src/node/Makefile
  src/node/control_timer.go
  src/node/core.go
  src/node/core_test.go
  src/node/node.go
  src/node/node_difftool.go
  src/node/node_test.go
  src/node/peer_selector2.go
  src/node/state.go
  src/peers/Makefile
  src/peers/peer.pb.go
  src/poset/Makefile
  src/poset/badger_store.go
  src/poset/badger_store_test.go
  src/poset/block.pb.go
  src/poset/event.go
  src/poset/event.pb.go
  src/poset/flagTableWrapper.pb.go
  src/poset/frame.pb.go
  src/poset/inmem_store.go
  src/poset/poset.go
  src/poset/poset_test.go
  src/poset/root.pb.go
  src/poset/roundInfo.pb.go
  src/proxy/Makefile
  src/proxy/internal/grpc.pb.go
  src/service/Makefile
  src/utils/Makefile
  src/version/Makefile
Labels: bug, enhancement

#103 Add threadsafe node state.
  src/node/node.go
  src/node/node_test.go
  src/node/state.go
  src/node/state_test.go
Labels: enhancement

#105 Embedding nodestate to node structure.
  src/node/node.go
  src/node/node_test.go
Labels: enhancement

#108 https://golangci.com/r/github.com/Fantom-foundation/go-lachesis
  cmd/dummy_client/main.go
  cmd/lachesis/commands/run.go
  cmd/lachesis/commands/run_lachesis.go
  cmd/lachesis/commands/run_lachesis_multi.go
  cmd/network/commands/proxy.go
  cmd/network/commands/run.go
  src/common/errors.go
  src/common/hash32.go
  src/common/rolling_index.go
  src/common/rolling_index_map.go
  src/common/test_logger.go
  src/crypto/hash.go
  src/crypto/pem_key.go
  src/crypto/utils.go
  src/difftool/result.go
  src/difftool/sort.go
  src/dummy/client.go
  src/dummy/state.go
  src/lachesis/lachesis.go
  src/log/hook.go
  src/mobile/handlers.go
  src/mobile/mobile_app_proxy.go
  src/mobile/mobile_config.go
  src/mobile/node.go
  src/net/commands.go
  src/net/inmem_transport.go
  src/net/net_transport.go
  src/node/common.go
  src/node/config.go
  src/node/control_timer.go
  src/node/core.go
  src/node/debug.go
  src/node/graph.go
  src/node/node.go
  src/node/node_difftool.go
  src/node/nodebug.go
  src/node/peer_selector.go
  src/node/peer_selector2.go
  src/node/state.go
  src/peers/peer.go
  src/peers/peers.go
  src/poset/badger_store.go
  src/poset/block.go
  src/poset/caches.go
  src/poset/debug.go
  src/poset/event.go
  src/poset/frame.go
  src/poset/inmem_store.go
  src/poset/poset.go
  src/poset/poset_test.go
  src/poset/root.go
  src/poset/roundInfo.go
  src/proxy/handlers.go
  src/proxy/inmem_app.go
  src/proxy/inmem_test.go
  src/service/service.go
  src/utils/util.go
  src/version/version.go
  tester/tester.go
Labels: enhancement

#109 Fix TestJSONPeers test.
  src/peers/json_peers.go
Labels: in progress

#111 Golangci
  src/dummy/client_test.go
  src/node/core.go
  src/node/core_test.go
  src/node/node_test.go
  src/poset/poset.go
  src/poset/poset_test.go
  src/proxy/inmem_app.go
Labels: enhancement

#113 Removed graph assets, render this in a separate project
  src/service/service.go
  src/service/static/assets/core.js
  src/service/static/assets/draw.js
  src/service/static/assets/index.js
  src/service/static/index.html
Labels: enhancement

#112 Net transport sizelimit
  src/net/inmem_transport.go
  src/net/inmem_transport_test.go
  src/net/net_transport_test.go
  src/net/transport_test.go
  src/node/core.go
  src/node/core_test.go
  src/node/node.go
  src/node/node_difftool.go
Labels: enhancement, in progress

#114 Improved peer smart selector
  src/node/peer_selector2.go
  src/node/peer_selector2_test.go
  src/node/peer_selector_test.go
Labels: enhancement, in progress

#117 [goreleaser] Init
  .goreleaser.yml
  scripts/daemon/go-lachesis.service
  scripts/multi_run.bash
  scripts/preinstall.bash
  scripts/set_globals.bash
Labels: enhancement, in progress

#118 [src/node/node.go] Utilise SyncLimit
  src/node/node.go
Labels: enhancement, in progress
