Repository Fantom-foundation/go-lachesis, pull requests merged in 2018-10, with the labels that each got.

#41 Docker and out-of-docker builds; proxy leak handling; tester improvements
  .dockerignore
  .gitignore
  Dockerfile
  README.md
  demo/scripts/run-testnet.sh
  glide.lock
  glide.yaml
  scripts/docker/Dockerfile
  scripts/docker/README.md
  scripts/docker/clean.bash
  scripts/docker/install_deps.bash
  scripts/docker/network.bash
  scripts/docker/scale.bash
  scripts/docker/set_globals.bash
  scripts/docker/spin.bash
  scripts/docker/spin_multi.bash
  scripts/spin_processes.bash
  src/net/mqtt.go
  src/node/node.go
  src/node/node_test.go
  src/poset/badger_store.go
  src/poset/block.go
  src/poset/inmem_store.go
  src/poset/poset_test.go
  src/proxy/lachesis/socket_lachesis_proxy_client.go
  src/utils/text.go
  tester/tester.go
Labels: bug, enhancement

#43 Fix for block signature verification error; new doc file; improve spin_processes.bash
  cmd/lachesis/commands/config.go
  docker/makefile
  docs.md
  scripts/spin_processes.bash
  src/lachesis/lachesis.go
  src/lachesis/lachesis_config.go
  src/log/hook.go
  src/mobile/node.go
  src/net/net_transport.go
  src/node/config.go
  src/node/core.go
  src/poset/block.go
  src/poset/poset.go
  src/proxy/app/inmem_app_proxy.go
  src/proxy/app/socket_app_proxy.go
  src/proxy/lachesis/socket_lachesis_proxy.go
Labels: bug, enhancement

#45 Add in-degree map
  src/node/core.go
  src/node/core_test.go
Labels: enhancement

#49 Fixed types and updated glide
  .gitignore
  cmd/lachesis/commands/run.go
  glide.lock
  glide.yaml
  src/net/mqtt.go
  src/node/core.go
  src/node/node.go
  src/poset/poset.go
  tester/tester.go
Labels: bug, enhancement

#44 Rb websocket proxy tx only
  src/proxy/socket/app/socket_app_proxy.go
  src/proxy/socket/app/socket_app_proxy_websocket_server.go
  src/proxy/socket/lachesis/socket_lachesis_proxy.go
  src/proxy/socket/lachesis/socket_lachesis_proxy_websocket_client.go
  tester/tester.go
Labels: enhancement

#50 Graph Implementation service
  src/node/graph.go
  src/node/node.go
  src/poset/event.go
  src/poset/roundInfo.go
  src/service/service.go
  src/service/static/assets/core.js
  src/service/static/assets/draw.js
  src/service/static/assets/index.js
  src/service/static/index.html
Labels: enhancement

#51 Minor Dockerfile fixes
  Dockerfile
  scripts/docker/Dockerfile
Labels: bug

#59 Issue #28 solution
  glide.lock
  glide.yaml
  src/proxy/birpc/birpc.go
  src/proxy/birpc/birpc_test.go
  src/proxy/grpc_app.go
  src/proxy/grpc_lachesis.go
  src/proxy/grpc_test.go
  src/proxy/internal/grpc.pb.go
  src/proxy/internal/grpc.proto
  src/proxy/socket/app/websocket_app_proxy.go
  src/proxy/socket/lachesis/websocket_lachesis_proxy.go
  src/proxy/socket/socket_proxy_test.go
Labels: enhancement

#57 Testing improvements
  .gitlab-ci.yml
  cmd/lachesis/commands/keygen.go
  cmd/lachesis/commands/run.go
  cmd/lachesis/commands/run_lachesis_multi.go
  cmd/lachesis/main_profile.go
  docs/README.md
  scripts/docker/clean.bash
  scripts/docker/network.bash
  scripts/docker/spin_multi.bash
  scripts/multi_build.bash
  scripts/multi_run.bash
  sonar-project.properties
  src/mobile/.gitignore
  src/mobile/handlers.go
  src/net/client_socket.go
  src/net/server_socket.go
  src/node/core.go
  src/node/peer_selector.go
  src/poset/poset.go
  src/poset/store.go
  src/proxy/handlers.go
  src/proxy/inapp/inapp_proxy.go
  src/proxy/inmem/inmem_proxy.go
  src/proxy/proxy.go
  src/service/service.go
  tester/tester.go
Labels: bug, enhancement
